version: '3.9'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - type: volume
        target: /database
    environment:
      POSTGRES_DB: webshop
      POSTGRES_USER: webshopclient
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432

  testdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: webshoptest
      POSTGRES_USER: webshoptestclient
      POSTGRES_PASSWORD: secret
    ports:
      - 5433:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: webshop@email.com
      PGADMIN_DEFAULT_PASSWORD: emailsecret
    ports:
      - 8080:80