version: '3.9'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - type: volume
        target: /database
    environment:
      POSTGRES_PASSWORD: secret

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080